pipeline {
    agent any
    tools {
        nodejs 'node20'
    }
    environment {
        IMAGE_NAME = 'muhnnad/devops-status-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DEV_OVERLAY = 'app/k8s/overlays/dev'
        // No KUBECONFIG: ArgoCD owns the cluster now. This pipeline never
        // runs kubectl, so Jenkins no longer needs cluster credentials at all.
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                script {
                    // The "Update dev manifest" stage below pushes a commit back to main.
                    // Without this guard that push would trigger another build, which would
                    // push again, forever. Manifest-only commits are tagged [skip ci].
                    def lastMessage = sh(script: 'git log -1 --pretty=%B', returnStdout: true).trim()
                    env.SKIP_BUILD = lastMessage.contains('[skip ci]') ? 'true' : 'false'
                    if (env.SKIP_BUILD == 'true') {
                        echo 'Manifest-only commit from a previous build. Nothing to do.'
                    }
                }
            }
        }

        stage('Build') {
            when { environment name: 'SKIP_BUILD', value: 'false' }
            steps {
                dir('app') {
                    script {
                        env.APP_VERSION = sh(
                            script: "grep -m1 '\"version\"' package.json | sed -E 's/.*\"version\": *\"([^\"]+)\".*/\\1/'",
                            returnStdout: true
                        ).trim()
                    }
                    sh 'npm ci'
                    sh 'npm test'
                    sh 'npm run build'
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push image') {
            when { environment name: 'SKIP_BUILD', value: 'false' }
            steps {
                sh "echo \"${DOCKERHUB_CREDENTIALS_PSW}\" | docker login -u \"${DOCKERHUB_CREDENTIALS_USR}\" --password-stdin"
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('Update dev manifest') {
            when { environment name: 'SKIP_BUILD', value: 'false' }
            steps {
                script {
                    def shortCommit = env.GIT_COMMIT.take(7)
                    def repoUrl = env.GIT_URL ?: 'https://github.com/MohnadBabgi/Jenkins-project.git'

                    // Rewrite the build metadata the status page displays.
                    writeFile file: "${env.DEV_OVERLAY}/patch-deployment.yaml", text: """\
# Build metadata for whatever Jenkins last pushed to dev.
# This file is REGENERATED by the Jenkins pipeline on every build — don't hand-edit it,
# your changes will be overwritten on the next push to main.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-status-app
spec:
  template:
    spec:
      containers:
        - name: devops-status-app
          env:
            - name: APP_VERSION
              value: "${env.APP_VERSION}"
            - name: GIT_COMMIT
              value: "${shortCommit}"
            - name: BUILD_NUMBER
              value: "${env.BUILD_NUMBER}"
            - name: REPO_URL
              value: "${repoUrl}"
            - name: BUILD_URL
              value: "${env.BUILD_URL}"
"""
                }

                // Point dev at the image this build just pushed. ArgoCD picks this up.
                sh "sed -i -E 's|^([[:space:]]*newTag:[[:space:]]*).*|\\1\"${IMAGE_TAG}\"|' ${DEV_OVERLAY}/kustomization.yaml"

                sh "git diff -- ${DEV_OVERLAY}"

                withCredentials([usernamePassword(
                    credentialsId: 'github-credentials',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh """
                        git config user.email 'jenkins@ci.local'
                        git config user.name 'Jenkins'
                        git add ${DEV_OVERLAY}
                        git diff --cached --quiet && echo 'No manifest change to push.' && exit 0
                        git commit -m 'Deploy build ${BUILD_NUMBER} to dev [skip ci]'
                        git push "https://\${GIT_USER}:\${GIT_TOKEN}@github.com/MohnadBabgi/Jenkins-project.git" HEAD:main
                    """
                }
            }
        }

        stage('Verify dev') {
            when { environment name: 'SKIP_BUILD', value: 'false' }
            steps {
                // ArgoCD syncs on its own schedule, so this polls rather than
                // assuming the rollout already happened.
                sh '''
                    for attempt in $(seq 1 60); do
                      if curl -sf http://localhost:30080/api/status \
                           | grep -q "\\"buildNumber\\":\\"${BUILD_NUMBER}\\""; then
                        echo "dev is serving build ${BUILD_NUMBER}"
                        exit 0
                      fi
                      echo "waiting for ArgoCD to sync dev (attempt ${attempt}/60)"
                      sleep 5
                    done
                    echo "dev did not reach build ${BUILD_NUMBER} within 5 minutes"
                    exit 1
                '''
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
        }
    }
}
